<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHgdx6xd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHgdx6xd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHgdx6xd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHgdx6xd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHgdx6xd\appProdProjectContainer([
    'container.build_hash' => 'Hgdx6xd',
    'container.build_id' => '785b2660',
    'container.build_time' => 1560541240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHgdx6xd');
