<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order_preferences.gift_options' shared service.

return $this->services['form.type.order_preferences.gift_options'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderPreferences\GiftOptionsType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : ($this->services['prestashop.adapter.legacy.context'] = new \PrestaShop\PrestaShop\Adapter\LegacyContext())) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.adapter.data_provider.currency']) ? $this->services['prestashop.adapter.data_provider.currency'] : $this->load('getPrestashop_Adapter_DataProvider_CurrencyService.php')) && false ?: '_'}->getDefaultCurrencyIsoCode(), ${($_ = isset($this->services['prestashop.adapter.data_provider.tax']) ? $this->services['prestashop.adapter.data_provider.tax'] : ($this->services['prestashop.adapter.data_provider.tax'] = new \PrestaShop\PrestaShop\Adapter\Tax\TaxRuleDataProvider())) && false ?: '_'}->getTaxRulesGroupChoices());
