<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.kpi_row.factory.translations_page' shared service.

return $this->services['prestashop.core.kpi_row.factory.translations_page'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowFactory(${($_ = isset($this->services['prestashop.adapter.kpi.enabled_languages']) ? $this->services['prestashop.adapter.kpi.enabled_languages'] : $this->load('getPrestashop_Adapter_Kpi_EnabledLanguagesService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.kpi.main_country']) ? $this->services['prestashop.adapter.kpi.main_country'] : $this->load('getPrestashop_Adapter_Kpi_MainCountryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.kpi.translations']) ? $this->services['prestashop.adapter.kpi.translations'] : $this->load('getPrestashop_Adapter_Kpi_TranslationsService.php')) && false ?: '_'});
