<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.presenter.module' shared service.

return $this->services['prestashop.adapter.presenter.module'] = new \PrestaShop\PrestaShop\Adapter\Presenter\Module\ModulePresenter(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : ($this->services['prestashop.adapter.legacy.context'] = new \PrestaShop\PrestaShop\Adapter\LegacyContext())) && false ?: '_'}->getContext()->currency, ${($_ = isset($this->services['prestashop.adapter.formatter.price']) ? $this->services['prestashop.adapter.formatter.price'] : ($this->services['prestashop.adapter.formatter.price'] = new \PrestaShop\PrestaShop\Adapter\Product\PriceFormatter())) && false ?: '_'});
