<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.smarty' shared service.

$this->services['prestashop.smarty'] = $instance = new \PrestaShop\TranslationToolsBundle\Smarty();

$instance->setCompileDir(($this->targetDirs[0].'/smarty'));
$instance->forceCompile(true);

return $instance;
